### ISSUE TITLE
ショートカットキーによる撮影に対応する

### ISSUE THREAD

**Issue by takanakahiko** [aktsk/screenshot-for-app-store#2]

**Comment by cllightz** [comment]
キーバインドは自由に設定できるようにしたい。

**Comment by cllightz** [comment]
#5 と同様に、Inspector上で設定できるのがベストだと思います。

**Comment by takanakahiko** [comment]
いえ、これはそもそも実装としては固定にせざるを得ないと思います。
重複時はShortcut Managerを私用すれば問題ないかと（記事最下部）

https://kan-kikuchi.hatenablog.com/entry/Hotkey

**Comment by cllightz** [comment]
Shortcut Managerで十分そうですね。
CaptureScreenshotsForAppStore側ではわざわざショートカットキーに対応しなくても良いかもしれません。

**Comment by takanakahiko** [comment]
一応閉じときます〜
